#!/bin/bash

if [ -z $1 ]; then
    printf "\E[0;31;40mPlease choose a network interface...\E[0m\n"
    exit
fi
if [ -z $2 ]; then
    printf "\E[0;31;40mLack of domain URL...\E[0m\n"
    exit
fi

sudo ngrep -t '^(GET|POST|PUT)' "src host $2 and tcp and dst port 80"
